config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :apps, only: [ :index, :show, :new, :create ] do
    resources :votes, only: [ :create ]
    resources :comments, only: [ :index, :show, :create, :edit ]
  end
  resources :votes, only: [ :update ]

  resources :connections, only: [ :create ]

  resources :comments, only: [ :update, :destroy ]

  get "/feed", to: "feeds#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "profile", to: "pages#profile"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm transparent fixed">
  <div class="container-fluid ">
    <div class="d-flex">
      <% if user_signed_in? %>
        <%= link_to "ToolBox", apps_path, class:"ToolBox" %>
      <% else %>
        <%= link_to "ToolBox", root_path, class:"ToolBox" %>
      <% end %>
    </div>

    <% if user_signed_in? %>
     <div class="d-flex">
        <%= link_to feed_path do %>
        <button type="button" class="feed-btn">
          <span class="fas fa-newspaper fa-2xl px-1 feed" style="color: #ffffff;padding-top: 15px;" ></span>
        </button>
        <% end %>


        <button type="button" class="profile-btn" data-bs-toggle="dropdown" aria-expanded="false">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "image-form border border-white profile-btn", crop: :fill, style: "height: 32px; width: 32px; box-shadow: 2px 2px 4px black;" %>
          <% else %>
            <%= image_tag "avatar_placeholder.jpg", class: "image-form border border-white profile-btn", crop: :fill, style: "height: 32px; width: 32px; box-shadow: 2px 2px 4px black;" %>
          <% end %>
        </button>
        <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end">
          <%= link_to "Profile", profile_path, class: "dropdown-item" %>
          <%= link_to "Home", root_path, class: "dropdown-item" %>
          <li><hr class="dropdown-divider"></li>
          <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </ul>
     </div>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
    <% end %>
  </div>
</div>

app/views/shared/_user_activity.html.erb
<div class="apps">
  <% feed_items = @comments + @votes %>
  <% feed_items.sort_by! { |item| item.updated_at }.reverse! %>
  <% feed_items.each do |item| %>
    <div class="app-card">
      <% case item.class.to_s %>
      <% when 'Comment' %>
        <div class="comment-item">
          <p><strong>New comment - <%= link_to item.user.username, profile_path(user: item.user.id), class: "text-decoration-none" %> on <%= link_to item.app.name, app_path(item.app) %>:" </strong> <%= item.comment.truncate(App::COMMENT_LENGTH) %>".</p>
        </div>
      <% when 'Vote' %>
        <div class="vote-item">
          <p><strong>New vote - <%= link_to item.user.username, profile_path(user: item.user.id), class: "text-decoration-none" %> </strong>  voted <%= item.vote %> on <%= link_to item.app.name, app_path(item.app) %></p>
        </div>
      <% else %>
        <p>Unknown activity type</p>
      <% end %>
    </div>
  <% end %>
</div>