config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :apps, only: [ :index, :show, :new, :create ] do
    resources :votes, only: [ :create ]
    resources :comments, only: [ :index, :show, :create, :edit ]
  end
  resources :votes, only: [ :update ]

  resources :connections, only: [ :create ]

  resources :comments, only: [ :update, :destroy ]

  get "/feed", to: "feeds#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "profile", to: "pages#profile"
end

app/views/pages/_users_list.html.erb
<div class="p-3 search-results mb-4" data-add-connection-target="list">
  <ul>
    <% users.each do |user| %>
      <li class="search-results"><%= user.username %> <%= link_to "Add", connections_path(receiver_id: user), data: { turbo_method: :post } %></li>
    <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="container-2  opening-section text-center">
  <div class="p-3">
    <h1 class="text-white p-3">Empower Your Workflow with the Right Tools</h1>
    <p class="text-white">Discover a curated collection of digital tools and software to streamline your work. Whether you're a startup or a large enterprise, ToolBox is here to help you make informed choices for your workplace.</p>
  </div>



  <div class="scroll">
    <h1 class="text-white text-center pt-3" >Explore Tools</h1>
    <% if user_signed_in? %>
      <div class="text-center mt-4">
        <%= link_to "Search", apps_path, class:"btn btn-primary"%>
      </div>
    <% else %>
      <div class="text-center mt-4">
        <%= link_to "Sign Up",  new_user_registration_path, class:"btn btn-primary"%>
      </div>
    <% end %>

    <div class="m-scroll">
      <span class="moving-logo"><%= image_tag "notion.png", alt: "Notion Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "asana.png", alt: "Asana Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "ninjaone.png", alt: "Ninjaone Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "trello.webp", alt: "Trello Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "shopify.png", alt: "Shopify Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "mailchimp.png", alt: "Mailchimp Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "canva.png", alt: "Canva Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "notion.png", alt: "Notion Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "asana.png", alt: "Asana Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "ninjaone.png", alt: "Ninjaone Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "sonar.png", alt: "Sonar Logo", class:"logozzz" %></span>
    </div>

    <div class="m-scroll-2">
      <span class="moving-logo"><%= image_tag "salesforce.png", alt: "Salesforce Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "vyond.png", alt: "Vyond Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "sentinelone.png", alt: "Sentinelone Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "jamf-pr.png", alt: "Jamf Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "salesforce.png", alt: "Salesforce Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "microsoft.png", alt: "Microsoft Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "vyond.png", alt: "Vyond Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "sentinelone.png", alt: "Sentinelone Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "trello.webp", alt: "Trello Logo", class:"logozzz" %></span>
      <span class="moving-logo"><%= image_tag "jamf-pr.png", alt: "Jamf Logo", class:"logozzz" %></span>
    </div>
  </div>
</div>

<div class="container container-fluid">
  <h3 class="text-white text-center py-4 ">About us</h3>
  <p class="text-white pt-2" >
    ToolBox is a user friendly web application for startups, people who work in tech aswell as big companies
    who are unsure which digital tools or software they should use at their workplace.
    With ToolBox you are able to search and select the best tools fitting your work-stlye and based on your friends's personal recommandations!
    With our upvote and downvote function you will be able to take this experience anywhere, anytime.
  </p>


  <footer class="home-footer py-5 ps-3">
    <div class="container-fluid">
      <div class="row">
        <div data-controller="reveal">
          <div class="d-flex flex-row">
            <h4 data-action="click->reveal#toggle" class="text-white">Contact us</h4>
            <i class="fa-solid fa-caret-down px-2 mt-1" style="color: #ffffff;"></i>
          </div>
          <div class="dropdown-content d-none" data-reveal-target="toggle">
            <div class="contact-info d-flex">
              <i class="fa-solid fa-phone " style="color: #ffffff; padding-right: 5px; "></i>
              <p class="text-white">+1 (123) 456-7890</p>
            </div>
            <div class="contact-info d-flex">
              <i class="fa-solid fa-envelope " style="color: #ffffff; padding-right: 5px;"></i>
              <p class="text-white">Semih@gmail.com</p>
            </div>
            <div class="contact-info d-flex">
              <i class="fa-brands fa-whatsapp fa-lg" style="color: #ffffff; padding-right: 5px;"></i>
              <p class="text-white">+62 8233 7809 347</p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid pt-5">
      <div class="row">
        <div data-controller="reveal">
          <div class="d-flex flex-row">
            <h4 data-action="click->reveal#toggle" class="text-white">Social Media</h4>
            <i class="fa-solid fa-caret-down px-2 mt-1" style="color: #ffffff;"></i>
          </div>
          <div class="dropdown-content d-none" data-reveal-target="toggle">
            <div class="contact-info d-flex">
              <i class="fa-brands fa-instagram" style="color: #ffffff; padding-right: 5px;"></i>
              <p class="text-white">ToolBox</p>
            </div>
            <div class="contact-info d-flex">
              <i class="fa-brands fa-x-twitter" style="color: #ffffff; padding-right: 5px;"></i>
              <p class="text-white">SEMIH_FOR_PRESIDENT</p>
            </div>
            <div class="contact-info d-flex">
              <i class="fa-brands fa-facebook-f" style="color: #ffffff; padding-right: 5px;"></i>
              <p class="text-white">semih_fb</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/pages/profile.html.erb
<div class="container p-3 vh-100">
  <div class="border-radius card-profile">
    <% profile_for_other_user = params.has_key?(:user_id)  %>
    <% if profile_for_other_user %>
      <% user_for_profile = User.find(params["user_id"]) %>
      <h1 class="fw-bold">About <%= user_for_profile.username %></h1>
    <% else %>
      <h1 class="fw-bold">Your Account</h1>
      <% user_for_profile = current_user %>
    <% end %>
    <div class="card-profile__content">
      <% if user_for_profile.photo.attached? %>
        <%= cl_image_tag user_for_profile.photo.key, class: "image-form border border-white" %>
      <% else %>
        <%= image_tag "avatar_placeholder.jpg", class: "image-form border border-white" %>
      <% end %>
      <div>
        <div class="fw-bold mb-1 fs-2"><%= user_for_profile.username %></div>
        <div class="mb-3"><%= user_for_profile.email %></div>
        <% if user_for_profile == current_user %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "button-border btn btn-primary btn-light-blue" %>
        <% end %>
      </div>
    </div>
  </div>

  <% if user_for_profile == current_user %>
    <div class="border-radius card-profile">
      <div>
        <h2 class="fw-bold mb-4 btn btn-primary btn-light-blue button-border" data-bs-toggle="modal" data-bs-target="#exampleModal">Your Connections <i class="fa-solid fa-arrow-up-right-from-square"></i></h2>
      </div>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable ">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="exampleModalLabel">Your connections</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div>
                <% current_user.friends.each do |friend| %>
                  <div class="friends--box-wrapper d-flex">
                    <% if friend.photo.attached? %>
                      <div> <%= cl_image_tag friend.photo.key, class: "image-form border border-white", height: 40, width: 40, crop: :fill %> </div>
                    <% else %>
                      <div> <%= image_tag "avatar_placeholder.jpg", class: "image-form border border-white", height: 40, width: 40, crop: :fill %> </div>
                    <% end %>
                    <div class="p-2"><h2><%= friend.username%></h2></div>
                  </div>
                  <% end %>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <% if current_user.sent_connections.find_by(receiver: nil) %>
        <% link = "https://toolbox.osc-fr1.scalingo.io/users/sign_up?connection_id=#{user_for_profile.sent_connections.last.id}" %>
      <% end %>

      <div class="add-user my-3" data-controller="add-connection">
        <%= form_with url: profile_path, method: :get, html: {class: "mb-4", data: {add_connection_target: "form"}} do |f| %>
          <%= f.label :query, "Add a User", class: "mb-1 fw-bold me-1" %> <i class="fa-solid fa-caret-down"></i>
          <%= f.text_field :query, placeholder: "Search by username...",
                            class: "form-control",
                            value: params[:query],
                            data: {
                              add_connection_target: "input",
                              action: "keyup->add-connection#update"
                            }
                          %>
        <% end %>

        <%= render "users_list", users: @users %>
      </div>

      <div class="border-top mt-5">
        <h3 class="mt-4">Invite a new User</h3>
          <div data-controller="clipboard" data-clipboard-feedback-text-value="Copied!">
            <div class="d-flex justify-content-between my-3">
              <%= link_to connections_path, data: { turbo_method: :post }, class: "btn btn-primary btn-middle-blue button-border" do %>
                <span>Generate Link</span><i class="fa-solid fa-plus ms-1"></i>
              <% end %>
              <button class="btn btn-primary btn-middle-blue button-border" data-action="click->clipboard#copy">Copy link <i class="fa-solid fa-copy"></i> </button>
            </div>
            <div>
              <input class="w-100" data-clipboard-target="input" type="text" value="<%= link %>" readonly>
            </div>
          </div>
      </div>
    </div <% profile_for_other_user  %>>
  <% end %>

  <% if profile_for_other_user %>
    <div class="mt-5 ">
      <h4 class="text-center my-3 text-white fw-bold">Recent Activities</h4>
      <%= render "shared/user_activity" %>
    </div>
  <% end %>
</div>