config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :apps, only: [ :index, :show, :new, :create ] do
    resources :votes, only: [ :create ]
    resources :comments, only: [ :index, :show, :create, :edit ]
  end
  resources :votes, only: [ :update ]

  resources :connections, only: [ :create ]

  resources :comments, only: [ :update, :destroy ]

  get "/feed", to: "feeds#index"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "profile", to: "pages#profile"
end

app/views/apps/_card.html.erb
<div class="app-card">
  <div class="card-content-left">
    <%= link_to  app_path(app), class: "app-title" do %>
      <%= app.name.truncate(App::NAME_LENGTH) %>
    <% end %>

    <div class="app-body">
      <%= link_to app_path(app) do %>
        <%= image_tag app.logo_url, width: "80px", height: "80px", crop: :fill, class: "tool-icon" %>
      <% end %>

      <div class="app-details">
        <div class="app-categories">
          <% app.categories.map(&:name).each do |category| %>
            <span class="category-name"><%= category.truncate(App::CATEGORY_LENGTH) %></span>
          <% end %>
        </div>

        <div class="app-upvoters">
          <div class="connections">
            <% app.votes.where(vote: 1, user: current_user.friends).each_with_index do |vote, index| %>
              <% if vote.user.photo.attached? %>
                <%= link_to profile_path(user_id: vote.user.id), class: ("shift-left" if index > 0) do %>
                  <%= cl_image_tag vote.user.photo.key, class: "avatar-squared", width: 25, height: 25, crop: :fill %>
                <% end %>
              <% else %>
                <%= link_to profile_path(user_id: vote.user.id), class: ("shift-left" if index > 0) do %>
                  <%= image_tag "avatar_placeholder.jpg", class: "avatar-squared", width: 25, height: 25, crop: :fill  %>

                <% end %>
              <% end %>
            <% end %>
          </div>

          <div class="number-of-upvotes">
            <p data-bs-toggle="modal" data-bs-target="#exampleModal<%= app.id %>" class="thumbs-up-vote"><small>👍</small> <%= app.votes.where(vote: 1, user: current_user.friends).count %></p>
          </div>
        </div>

        <div class="app-downvoters">
          <div class="connections">
            <% app.votes.where(vote: -1, user: current_user.friends).each_with_index do |vote, index| %>
              <% if vote.user.photo.attached? %>
                <%= link_to profile_path(user_id: vote.user.id), class: ("shift-left" if index > 0) do %>
                <%= cl_image_tag vote.user.photo.key, class: "avatar-squared", width: 25, height: 25, crop: :fill %>
                <% end %>
              <% else %>
                <%= link_to profile_path(user_id: vote.user.id), class: ("shift-left" if index > 0) do %>
                  <%= image_tag "avatar_placeholder.jpg", class: "avatar-squared", width: 25, height: 25, crop: :fill  %>
                <% end %>
              <% end %>
            <% end %>
          </div>

          <div class="number-of-upvotes">
            <p data-bs-toggle="modal" data-bs-target="#exampleModal<%= app.id %>" class="thumbs-down-vote"><small>👎</small> <%= app.votes.where(vote: -1, user: current_user.friends).count %></p>
          </div>

        </div>
      </div>
    </div>
  </div>
  <div class="votings">
    <div class="vote-num">
      <small class="total_votes"> <%= app.total_votes + app.total_vote_g2  %> </small>
    </div>
      <%= render "apps/vote_buttons", app: app %>
  </div>
</div>

app/views/apps/_list.html.erb
<div class="apps" id="apps_div" data-search-tools-target="list" data-filter-target="list">
  <% apps.each do |app| %>
    <div data-controller="votes">
      <%= render "apps/card", app: app %>
    </div>
  <% end %>
</div>

app/views/apps/_vote_buttons.html.erb
    <% if current_user.voted? app %>
      <% vote = current_user.vote_of(app) %>
      <div class="up mb-1">
        <%= button_to vote_path(vote, vote: (vote.upvoted? ? 0 : +1)),
                      method: :patch,
                      class: "vote #{vote.upvoted? ? "upvoted" : "upvote"}",
                      form: {
                        data: { action: "submit->votes#vote" }
                      } do %>
          <i class="fa-sharp fa-solid fa-chevron-up" style=""></i>
        <% end %>
      </div>

      <div class="down mt-1">
        <%= button_to vote_path(vote, vote: (vote.downvoted? ? 0 : -1)),
                      method: :patch,
                      class: "vote #{vote.downvoted? ? "downvoted" : "downvote"}",
                      form: {
                        data: { action: "submit->votes#vote" }
                      } do %>
          <i class="fa-sharp fa-solid fa-chevron-down" style=""></i>
        <% end %>
      </div>

    <% else %>
      <div class="up mb-1">
        <%= button_to app_votes_path(app, vote: +1),
                      method: :post,
                      class: "vote upvote",
                      form: {
                        data: { action: "submit->votes#vote" }
                      } do %>
          <i class="fa-sharp fa-solid fa-chevron-up" style=""></i>
        <% end %>
      </div>

      <div class="down mt-1">
        <%= button_to app_votes_path(app, vote: -1),
                      method: :post,
                      class: "vote downvote",
                      form: {
                        data: { action: "submit->votes#vote" }
                      } do %>
          <i class="fa-sharp fa-solid fa-chevron-down" style=""></i>
        <% end %>
      </div>
    <% end %>

app/views/apps/index.html.erb
<div class="container" data-controller="search-tools filter">
  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: apps_path, method: :get, class: "d-flex flew-grow-1", data: { search_tools_target: "form" } do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Type an app name",
              data: {
                search_tools_target: "input",
                action: "keyup->search-tools#update"
              }
          %>
      <% end %>
    </div>
  </div>

  <div class="filters">
    <div class="filter-category-button">
      <%= form_with(url: apps_path, method: :get, local: true, data: { filter_target: "form"}) do %>
        <%= select_tag :category_id,
                        options_from_collection_for_select(@categories, :id, :name, params[:category_id]),
                        include_blank: 'All Categories',
                        class: "category-form",
                        data: {
                          filter_target: "category",
                          action: "change->filter#submit"
                        } %>
      <% end %>
    </div>

    <div class="toggle-connection">
      <%= form_with(url: apps_path, method: :get, local: true, data: { filter_target: "form"}) do %>
        <label class="switch">
          <%= check_box :connections, :connections,
                          class: "opacity-0",
                          data: {
                            filter_target: "connections",
                            action: "change->filter#connections"
                          } %>
          <span class="slider">
          </span>
        </label>
      <% end %>
    </div>
  </div>

  <%= render "list", apps: @apps %>
</div>

app/views/apps/show.html copy.erb
<div class="container">
 <%= link_to apps_path, class: "backBtn" do %>
  <i class="fas fa-arrow-left"></i> Back
 <% end %>

  <div class="app-card mt-2">
    <div class="app d-flex flex-column justify-content mb-3 align-items-center">
      <div class="header d-flex mb-3">
            <%= image_tag @app.logo_url, width: "130px", height: "130px", crop: :fill %>
        <div class="header-content px-3">
          <div class="name"> <h3 class="fw-bold app-name"> <%= @app.name %> </h3> </div>
          <div class="category"> <p> <strong>Category:</strong>  <%= @app.categories.map(&:name).join(", ") %> </p> </div>
          <div class="upvotes"><strong>Total votes:</strong> <%= @app.total_votes %>   </div>
        </div>
      </div>
    </div>

  </div>
  <div class="app-card mt-2">
    <p class="px-3"><strong>Description:</strong></p>
    <div class="description px-2"> <%= @app.description.truncate(App::DESCRIPTION_LENGTH) %> </div>
    <div class="see-more px-2"> <%= link_to "see more", app_path %> </div>
  </div>
  <div class="app-card mt-2">
    <p class="px-3"><strong> Comments:</strong></p>
    <div class="description px-2"> <% @app.comments.each do |comment| %>
      <div class="bg-white px-2 mb-2">
        <% if comment.user.photo.attached? %>
            <%= cl_image_tag comment.user.photo.key, class: "rounded-circle border border-white", width: 25, height: 25, crop: :fill %>
          <% else %>
            <%= image_tag "avatar_placeholder.jpg", class: "rounded-circle border border-white", width: "25px", height: "25px", crop: :fill  %>
        <% end %>
        <strong> <%= link_to comment.user.username, profile_path(user_id: comment.user.id), class:"text-decoration-none" %>: </strong>
        <%= comment.comment %>
      </div>
    <% end %>
    </div>
  </div>

    <div class="description px-2">
      <%= form_with(model: [ @app, @app.comments.build ], local: true) do |form| %>
        <div class="field mb-3" style="">
          <%= form.text_area :comment, class: "form-control bg-glass", placeholder: "Type your comment here..." %>
        </div>
        <div class="actions mt-2">
          <%= form.submit "Add comment", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
</div>

app/views/apps/show.html.erb
<div class="container">
  <div data-controller="votes">
    <%= render "card", app: @app %>
  </div>
  <div class="card-glass card-glass--scrollable">
    <div class="card-glass--description">
      <p><%= @app.description %></p>
    </div>
  </div>
  <div data-controller="comments">
    <div class="comments-header">
    <div class="toggle-connection">
      <%= form_with(url: app_path(@app), method: :get, local: true, data: { filter_target: "form"}) do %>
        <label class="switch">
          <%= check_box :connections, :connections,
                          class: "opacity-0",
                          data: {
                            filter_target: "connections",
                            action: "change->comments#showConnections"
                          } %>
          <span class="slider">
          </span>
        </label>
      <% end %>
    </div>
      <h3>COMMENTS</h3>
      <div class="tile"><%= @app.comments.count %></div>
      <a href="#" class="btn-ghost" data-action="click->comments#addComment">Add Yours</a>
    </div>

    <div class="card-glass--scrollable" data-comments-target="commentsList">
        <%= render "comments/new", app: @app %>
        <div data-comments-target="all">
          <% @app.comments.each  do |comment|%>
            <%= render "comments/comment", comment: comment %>
          <% end %>
        </div>
        <div class="d-none" data-comments-target="connections">
          <% @app.comments.where(user: current_user.connections).each  do |comment|%>
            <%= render "comments/comment", comment: comment %>
          <% end %>
        </div>
    </div>
  </div>
</div>